# -*- coding: utf-8 -*-
"""Africa GDP Analysis_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXUpAkvLHQwpwFmjMahhy1LOBJHoPMZB

# Penn World Table - World Economics Data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Adding to mount google drive
from google.colab import drive
drive.mount('/content/drive')

#Load in the dataset
#econ_data = pd.read_excel("pwt100.xlsx", "Data")
econ_data = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Penn World Data Analysis/pwt100.xlsx", "Data")

econ_data.head(250)

econ_data.groupby("country")[["rgdpe", "rgdpe"]].describe()

#Load in a table that has a list of all the African countries
#This will be used to filter the econ_data dataset so that it contains data only for African countries
africa_reference= pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Penn World Data Analysis/list-african-countries-dependent-territory-286j.xlsx")
africa_reference.head(20)

#Extract the column with the African countries
african_countries = africa_reference["Country"].tolist()
african_countries

#Filter out the rows, keeping only those with African countries
africa_data = econ_data[econ_data["country"].isin(african_countries)]
africa_data

#Kepp only the columns that will be used as part of this analysis
africa_data = africa_data[["countrycode", "country", "year", "rgdpe", "rgdpo", "pop"]]

"""#### Determine the Mean Values for Each Country's Expenditure-Side Real GDP"""

#Calculate mean values for each country's Expenditure-side real GDP
africa_data.groupby('country')["rgdpe"].mean().sort_values(ascending=False)

##Calculate mean values for each country's Output-side real GDP
africa_data.groupby('country')["rgdpo"].mean().sort_values(ascending=False)

"""1) South Africa, Nigeria, Algeria, Egypt, and Morocco have the top 5 average expenditure side real GDPs, in order.<br>
2) In order, South Africa, Egypt, Nigeria, Algeria, and Morocco have the top 5 average output-side real GDPs.<br>
3) Djibouti, Guinea-Bissau, Comoros, Seychelles, Sao Tome and Principe have the bottom 5 average expenditure-side GDPs and output-side GDPs.<br>

#### Graph GDPs Over Time for the Top 5 Countries
"""

#Method 1
top5_gdpcountries_list = ["South Africa", "Nigeria", "Algeria", "Egypt", "Morocco"]
top5_gdps= africa_data[africa_data["country"].isin(top5_gdpcountries_list)]
#top5_gdps.groupby("country")["year", "rgdpe"].plot(x= "year", y="rgdpe")
top5_gdps.groupby("country").plot(x= "year", y="rgdpe")
#plt.xlabel("Year")
#plt.ylabel("Expenditure-side real GDP at chained PPPs,\n in mil. 2017US$")

#Method 2
#Uses a For Loop to loop through the list of the top 5 GDP countries
top5_gdpcountries_list = ["South Africa", "Nigeria", "Algeria", "Egypt", "Morocco"]
for country_name in top5_gdpcountries_list:
    country_graph= top5_gdps[top5_gdps["country"] == country_name]
    country_graph.plot(x="year", y="rgdpe")
    plt.title(country_name + " Expenditure-side real GDP Values Over Time")
    plt.xlabel("Year")
    plt.ylabel("Expenditure-side real GDP at chained PPPs,\n in mil. 2017US$")

"""#### Graph GDPs Over Time for the Bottom 5 Countries"""

#Create graphs for the bottom 5 GDP countries (Expenditure-side values)
bottom5_gdpcountries_list = ["Djibouti","Guinea-Bissau","Comoros","Seychelles","Sao Tome and Principe"]
bottom5_gdps = africa_data[africa_data["country"].isin(bottom5_gdpcountries_list)]
for country_name in bottom5_gdpcountries_list:
    country_graph= bottom5_gdps[bottom5_gdps["country"] == country_name]
    country_graph.plot(x="year", y="rgdpe")
    plt.title(country_name + " Expenditure-side real GDP Values Over Time")
    plt.xlabel("Year")
    plt.ylabel("Expenditure-side real GDP at chained PPPs,\n in mil. 2017US$")

"""### GDP values in the Last 30 Years for the Top 5 and Bottom 5 Countries"""

#Create a list for the years of the last 30 years to further filter the data
last_30yrs= range(1990, 2020, 1)
last_30yrs= list(last_30yrs)
last_30yrs

#test
#years_graph = top5_gdps[top5_gdps["year"].isin(last_decade)]
#years_graph

#Filter dataset to have only the last 30 years
africa_data_last30yrs = africa_data[africa_data.year.isin(last_30yrs)]
africa_data_last30yrs.head()

africa_data_last30yrs.groupby("country")["rgdpe"].mean().sort_values(ascending = False)

#Uses a For Loop to loop through the list of the top 5 GDP countries in the last 30 years
top5_30yrs_countries_list = ["South Africa", "Nigeria", "Algeria", "Egypt", "Morocco"]
for country_name in top5_30yrs_countries_list:
    country_graph= africa_data_last30yrs[africa_data_last30yrs["country"] == country_name]
    country_graph.plot(x="year", y="rgdpe")
    plt.title(country_name + " Expenditure-side real GDP Values Between 1990 and 2019")
    plt.xlabel("Year")
    plt.ylabel("Expenditure-side real GDP at chained PPPs,\n in mil. 2017US$")

#Uses a For Loop to loop through the list of the bottom 5 GDP countries in the last 30 years
bottom5_30yrs_countries_list = ["Djibouti", "Guinea-Bissau", "Seychelles", "Comoros", "Sao Tome and Principe"]
for country_name in bottom5_30yrs_countries_list:
    country_graph= africa_data_last30yrs[africa_data_last30yrs["country"] == country_name]
    country_graph.plot(x="year", y="rgdpe")
    plt.title(country_name + " Expenditure-side Real GDP Values Between 1990 and 2019")
    plt.xlabel("Year")
    plt.ylabel("Expenditure-side real GDP at chained PPPs,\n in mil. 2017US$")

#Calculate GDP per capita for all the African countries for each year of the last 30 yrs
africa_data_last30yrs["gdp_percapita"] = africa_data_last30yrs["rgdpe"]/africa_data_last30yrs["pop"]
africa_data_last30yrs.head(25)

#Calculate average for GDP per capita for all the African countries in the last 30 years
africa_data_last30yrs.groupby("country")["gdp_percapita"].mean().sort_values(ascending = False)

#Uses a For Loop to loop through the list of the top 5 GDP countries per capita in the last 30 years
top5_30yrs_countries_list_percapita = ["Seychelles", "Equatorial Guinea", "Mauritius", "Gabon", "Botswana"]
for country_name in top5_30yrs_countries_list_percapita:
    country_graph= africa_data_last30yrs[africa_data_last30yrs["country"] == country_name]
    country_graph.plot(x="year", y="gdp_percapita")
    plt.title(country_name + " Expenditure-side real GDP Values Per Capita Between 1990 and 2019")
    plt.xlabel("Year")
    plt.ylabel("Expenditure-side real GDP at chained PPPs,\n in mil. 2017US$")

#Uses a For Loop to loop through the list of the bottom 5 GDP countries per capita in the last 30 years
bottom5_30yrs_countries_list_percapita = ["Central African Republic", "Ethiopia", "Mozambique", "Liberia", "Burundi"]
for country_name in bottom5_30yrs_countries_list_percapita:
    country_graph= africa_data_last30yrs[africa_data_last30yrs["country"] == country_name]
    country_graph.plot(x="year", y="gdp_percapita")
    plt.title(country_name + " Expenditure-side Real GDP Values Per Capita Between 1990 and 2019")
    plt.xlabel("Year")
    plt.ylabel("Expenditure-side real GDP at chained PPPs,\n in mil. 2017US$")

"""##GDP Analysis of the Last Decade"""

#Filter dataset to have only the last decade
lastdecade= range(2010, 2020, 1)
africa_data_lastdecade = africa_data[africa_data.year.isin(lastdecade)]
africa_data_lastdecade.head()

africa_data_lastdecade.groupby("country")["rgdpe"].mean().sort_values(ascending = False)

#Calculate average for GDP per capita for all the African countries in the last decade
africa_data_lastdecade.groupby("country")["gdp_percapita"].mean().sort_values(ascending = False)

#Calculate GDP per capita for all the African countries for each year of the last decade
africa_data_lastdecade["gdp_percapita"] = africa_data_lastdecade["rgdpe"]/africa_data_lastdecade["pop"]
africa_data_lastdecade.head(25)

#africa_data["rgdpe"]/africa_data["pop"]
#africa_data.head(5)

#Calculate average for GDP per capita for all the African countries in the last decade
africa_data_lastdecade.groupby("country")["gdp_percapita"].mean().sort_values(ascending = False)

"""### Conclusions:
1) South Africa, Nigeria, Algeria, Egypt, and Morocco have the top 5 average expenditure side real GDPs, in order.<br>
2) In order, South Africa, Egypt, Nigeria, Algeria, and Morocco have the top 5 average output-side real GDPs.<br>
3) Djibouti, Guinea-Bissau,Comoros,Seychelles,Sao Tome and Principe have the bottom 5 average expenditure-side GDPs and output-side GDPs.<br>
4) Although South Africa has the highest GDP on average for the time period of the dataset, Nigeria and Egypt have had higher GDP values in the last 10 years.
5) The countries with the lowest average Expenditure-side GDP in the last decade are the Central African Republic, Guinea-Bissau, Seychelles, Comoros, and Sao Tome and Principe.
6) While the countries with the lowest average Expenditure-side GDP in the last decade  are the Central African Republic, Guinea-Bissau, Seychelles, Comoros, and Sao Tome and Principe, the countries with the lowest GDPs per capita are Niger, Liberia, Malawi, Central African Republic, and Burundi.
7) While South Africa, Egypt, and Nigeria have some of the largest economies in Africa, it may be worthwhile to draw lessons from the African countries with the highest GDPs per capita (Equatorial Guinea, Seychelles, Mauritius, Botswana, and Gabon).

### Areas for Further Study:
1. Use the complete dataset to compare Africa'S data to other continents.
"""